# Generated by Django 5.0.6 on 2024-07-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='point_of_sale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Point of Sale'),
        ),
    ]
