# Generated by Django 5.0.6 on 2024-07-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_point_of_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(blank=True, null=True, verbose_name='Event Link'),
        ),
    ]
