# Generated by Django 5.0.6 on 2024-07-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='bands', to='listings.photo'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.photo'),
        ),
    ]
