# Generated by Django 5.0.6 on 2024-07-10 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_band_likes_alter_band_user_alter_event_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='likes',
        ),
        migrations.AddField(
            model_name='band',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_bands', to=settings.AUTH_USER_MODEL),
        ),
    ]
