# Generated by Django 5.0.6 on 2024-07-12 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
