# Generated by Django 5.0.6 on 2024-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/'),
        ),
    ]
