# Generated by Django 5.0.6 on 2024-07-17 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='audio_file1',
            field=models.FileField(blank=True, null=True, upload_to='bands/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='band',
            name='audio_file2',
            field=models.FileField(blank=True, null=True, upload_to='bands/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='band',
            name='audio_file3',
            field=models.FileField(blank=True, null=True, upload_to='bands/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
