# Generated by Django 5.0.6 on 2024-07-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_band_audio_file1_band_audio_file2_band_audio_file3'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='audio_file1_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='audio_file2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='audio_file3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
